### ISSUE TITLE
Trying to add an already existing dependency fails silently

### ISSUE THREAD

**Issue by rock3r** [yigit/ArtifactFinder#7]
Imagine I have the dependency `a:b:1.0` in a module. Using the plugin I search for a class that lives in `a:b:1.1`, when I try to add that new version to the module it doesn't do anything, just fails silently. I suppose it should instead tell me if I want to upgrade (or downgrade) the dependency that exists already, or at least show an error.

**Comment by rcd27** [comment]
> Imagine I have the dependency `a:b:1.0` in a module. Using the plugin I search for a class that lives in `a:b:1.1`, when I try to add that new version to the module it doesn't do anything, just fails silently. I suppose it should instead tell me if I want to upgrade (or downgrade) the dependency that exists already, or at least show an error.

Showing the mistake of adding dependency is solved in #5

**Comment by rcd27** [comment]
Solved in #12
